// Mock data for development/fallback when MongoDB is not connected
export const mockMentors = [
  {
    _id: "1",
    name: "Sarah Chen",
    email: "sarah@example.com",
    role: "mentor",
    bio: "10+ years in software engineering with focus on full-stack development",
    skills: ["JavaScript", "React", "Node.js", "Python"],
    interests: ["Web Development", "Mentoring", "Open Source"],
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sarah",
    hourlyRate: 50,
    rating: 4.8,
    reviewCount: 24,
    isAvailable: true,
  },
  {
    _id: "2",
    name: "James Rodriguez",
    email: "james@example.com",
    role: "mentor",
    bio: "Product manager with experience at startups and Fortune 500 companies",
    skills: ["Product Management", "Leadership", "Strategy", "Analytics"],
    interests: ["Career Development", "Entrepreneurship", "Tech Industry"],
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=james",
    hourlyRate: 75,
    rating: 4.9,
    reviewCount: 31,
    isAvailable: true,
  },
  {
    _id: "3",
    name: "Emily Watson",
    email: "emily@example.com",
    role: "mentor",
    bio: "Data scientist specializing in machine learning and AI applications",
    skills: ["Python", "Machine Learning", "Data Science", "TensorFlow"],
    interests: ["AI/ML", "Research", "Mentoring"],
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=emily",
    hourlyRate: 80,
    rating: 4.7,
    reviewCount: 18,
    isAvailable: true,
  },
  {
    _id: "4",
    name: "Alex Thompson",
    email: "alex@example.com",
    role: "mentor",
    bio: "DevOps engineer focusing on cloud infrastructure and containerization",
    skills: ["Docker", "Kubernetes", "AWS", "CI/CD"],
    interests: ["Cloud Computing", "DevOps", "Infrastructure"],
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=alex",
    hourlyRate: 70,
    rating: 4.6,
    reviewCount: 15,
    isAvailable: true,
  },
  {
    _id: "5",
    name: "Maria Garcia",
    email: "maria@example.com",
    role: "mentor",
    bio: "UX/UI designer with portfolio at major tech companies",
    skills: ["UI Design", "UX Research", "Figma", "Design Systems"],
    interests: ["Design", "User Experience", "Creative Problem Solving"],
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=maria",
    hourlyRate: 65,
    rating: 4.8,
    reviewCount: 22,
    isAvailable: true,
  },
];
